### ISSUE TITLE
Thoughts on polaris-tokens ahead of refactor

### ISSUE THREAD

**Issue by martenbjork** [Shopify/polaris-tokens#117]
Hey! 👋

Having now worked with colors and polaris-tokens for a while, I wanted to get some thoughts out of my head. Happy to discuss all of this as we move forward!

### JSON and pure, exported functions 
When building tooling for tokens, you need the **inputs** and the **token functions** to be separate. 

For instance, you can have a tool read the `base.ts` file, run the transformations in the browser. You can then push the new `base.ts` file to github and rest assured that the same transformation will happen on the tokens server. The tool is essentially a GUI for the same function that exists in polaris-tokens.

If one of these parts isn't available, you can't build a tool. I ran into this problem several times during the creation of the color factory:

- **Inputs:** base.ts - Beause it's not JSON, I have to parse this using regular expressions after reading it from Github 😬
- **Color factory:** Hard-wired into Polaris at first. Then we exported it and it enabled me to run the factory in other contexts. Huge enabler.

Suggestions:

- All inputs are JSON files. We loose Typescript type checking, but we could replace that linting/tests on import.
- All transformations are simple, exported, pure functions, like so: `let tokens = createColorTokens(inputsJson)`.
- In general, think tooling-first. How can a third party implement polaris-tokens in their code base and get the same results?

### Dynamic outputs?
One big motivation behind GraphQL is that "what if you didn't have to implement an endpoint every time you wanted data in a new way?". Maybe that thinking applies to polaris-tokens as well?

Could we offer a dynamic format, like so:

`?type=colors&fields=name,figmaName,hsla&format=xml`

**Update**: Kaelig shared [this](https://polaris.shopify.com/api?query=%7B%0A%20%20designTokens%20%7B%0A%20%20%20%20name%0A%20%20%20%20value%0A%20%20%20%20originalValue%0A%20%20%20%20type%0A%20%20%20%20category%0A%20%20%20%20comment%0A%20%20%7D%0A%7D%0A) with me. Looks great!

### Theo and Gulp
- The Gulp pipeline makes it hard to reason about code, because there is so much abstraction going on.
- Theo's docs are quite limited. I found myself guessing and trying random things to get the right result. (Like, Tim and I, throwing the `includeMeta` flag [in here](https://github.com/Shopify/polaris-tokens/pull/110/files#diff-b9e12334e9eafd8341a6107dd98510c9))
- We have to jump through some pretty complicated hoops just to conform with Theo's way of doing things. [Here](https://github.com/Shopify/polaris-tokens/pull/110/files#diff-0e2eab60ec70ec199e67821b0be0fd69) we are iterating over JS, creating a YML string(!), feeding it to Theo to finally get some JSON output.

**Comment by tmlayton** [comment]
Hey! 👋 We should get together and talk more about this and what we can do to best support design tooling. I like the idea of Polaris Tokens offering a tier 3 API for this and agree the new color tokens pipeline is not in state I’m super happy with.

For the Theo pipeline, I like the idea of conforming data to pipe in without reformatting. This requires the color factory to change the shape of the data it creates, which is weird because then we have a private build tool dictating the shape of data passed to and generated by a public function. So in that case adapters I think makes some sense although it does make it complicated.

I’d like to spent some time together, map this out, and think of what our optimal setups might be.

**Comment by martenbjork** [comment]
Sounds great! I can jam on this whenever, so let me know when you're ready
to tackle this and I'll be there 🙂
