### ISSUE TITLE
Remove dist directory

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-tokens#167]
We shouldn't have a `dist` directory for polaris-tokens.
 - The site doesn't need it as it's shipped on herokuapp
 - Sketch palette is no longer supported
 - No reason for this
 - Has been forgotten about
 - Breaking change?

**Comment by alex-page** [comment]
@kaelig any thoughts on this?

**Comment by kaelig** [comment]
Yes! Thank you for the ping – I have a proposal for v3 that would freeze the current `dist` folder (and rename it to `dist-legacy`): https://github.com/Shopify/polaris-tokens/pull/169

It'd be great to get that in as part of polaris-react v6.

Happy to walk you through the changes next week.

**Comment by alex-page** [comment]
Feel free to make the change, we aren't going to add this to v6 as there is already a lot of work.
