### ISSUE TITLE
Update color names 🎨

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-tokens#21]
🎨 Colors were updated on <https://shopify.invisionapp.com/dsm/shopify/design-tokens>, please update this repository!

### Changes

Updated Polaris color names in InVision DSM. https://github.com/Shopify/polaris-tokens/pull/22

### Follow these steps

* [x] If you haven’t yet, clone this repository
  ```
  dev clone polaris-tokens
  dev up
  ```
* [x] Fetch tokens from Invision
  ```
  dev cd polaris-tokens
  git checkout master
  git pull
  git checkout -B update-color-tokens
  yarn getTokensFromInvision
  yarn dist
  yarn test -u
  ```
* [x] Update `CHANGELOG.md`
* [x] Commit & push the changes
  ```
  git commit -am "Update color tokens to the latest version"
  git push origin update-color-tokens
  ```
* [x] [Open a pull request][pr-link]

[pr-link]: https://github.com/Shopify/polaris-tokens/compare/master...update-color-tokens?expand=1&title=Update%20color%20tokens&body=Fixes%20%23XXX%20%3C!--%20replace%20XXX%20with%20the%20id%20of%20the%20original%20issue%20--%3E&assignees=kaelig,amrocha,tmlayton

**Comment by ry5n** [comment]
Why did the color names change? Wouldn’t this be a breaking change for polaris-react (or any project that consumes the tokens)?
