### ISSUE TITLE
Add color Title Bar

### ISSUE THREAD

**Issue by rosariopfernandes** [Shopify/polaris-tokens#29]
Looking at the [Color Guidelines](https://polaris.shopify.com/design/colors#section-guidelines), I can see there is a color named "Title Bar" that is not present on the [colors.android.xml](https://github.com/Shopify/polaris-tokens/blob/master/dist/colors.android.xml) file.

**Comment by kaelig** [comment]
Thank you for bringing this up. That would be because we currently don't encourage using this color – but that's about to change soon. Watch this space!
