### ISSUE TITLE
Polaris.clr unusable in Swift

### ISSUE THREAD

**Issue by santosgagbegnon** [Shopify/polaris-tokens#84]
### Issue:
The `Polaris.clr` file created produces errors when trying to load it in Swift. The [file](https://github.com/Shopify/polaris-tokens/blob/master/dist/Polaris.clr) can be found here. 

### What I've Noticed:
When initializing a `NSColorList` (the object that represents `.clr` files in Swift) using the `Polaris.clr`, I get this error: 
```
 Failed to initialize color list unarchiver: Error Domain=NSCocoaErrorDomain Code=4864
```
The interesting thing is that re saving the file using the `NSColorList`object and using that instead fixes this issue. 

### More Info:
I am also able to format the re saved `Polaris.clr` into XML1 format using mac's built in terminal command:
```plutil -convert xml1 /path/to/polaris.clr```
 however when I use the `Polaris.clr` in this repo, I get the following error:

```
 Property List error: Unexpected character  at line 1 / JSON error: JSON text did not start with array or object and option to allow fragments not set.
```

**Comment by kaelig** [comment]
It seems like Polaris.clr is currently importable by macOS's palette manager, but isn't readable via Swift.

I'm looking for a solution!

**Comment by kaelig** [comment]
Closing as we're going to avoid using clr files to import colors in Swift.
