### ISSUE TITLE
Pimp my README

### ISSUE THREAD

**Issue by kaelig** [Shopify/polaris-tokens#9]
This repository is all about design tokens, I guess the README could benefit from some design love!

Any ideas for a hero image, an illustration…?

cc @jessebc @ry5n @alyseadlard @sarahill

**Comment by alyseadlard** [comment]
💯 We could use this baby that was created for the internal Polaris newsletter: 
![unnamed](https://user-images.githubusercontent.com/2467207/38835300-054785a0-4180-11e8-9252-e569139a523a.png)

**Comment by alyseadlard** [comment]
The illustration team has a lot on their plate with Unite coming up, so if we want something custom we probably won't get it for another month at least.

**Comment by kaelig** [comment]
It looks great! @jkeussen would that be okay with you? (seems like it's going to be used in the Polaris Homepage too)

**Comment by jkeussen** [comment]
Yeah, that makes sense to me 👍
