### ISSUE TITLE
Beta (next release) of Tokens not found in rubygems

### ISSUE THREAD

**Issue by danrosenthal** [Shopify/polaris-tokens#99]
https://rubygems.org/gems/polaris_tokens/versions only lists 2.x.x and before releases, nothing from the 3.0.0-beta.x releases we've been doing from the `next` branch.

When trying to upgrade in a rails project, we run into this problem:

```
Could not find gem 'polaris_tokens (= 3.0.0.pre.beta.7)' in rubygems repository https://rubygems.org/ or installed
locally.
The source contains 'polaris_tokens' at: 1.1.0.pre.beta.1, 1.1.0.pre.beta.3, 1.1.0.pre.beta.7, 1.1.0, 1.2.0, 1.3.0,
1.3.1, 2.0.0, 2.1.1, 2.2.0, 2.3.0, 2.4.0.pre.beta.1, 2.4.0.pre.beta.2, 2.4.0, 2.5.0, 2.6.0, 2.7.0
```

**Comment by danrosenthal** [comment]
cc: @kaelig, @BPScott, @lwise

**Comment by BPScott** [comment]
Yeah looks @kaelig set it to skip gem publishing in the next branch https://github.com/Shopify/polaris-tokens/blob/next/shipit.yml#L14

**Comment by danrosenthal** [comment]
@lwise, we have moved these changes into a minor release of Polaris Tokens, which is available here: https://www.npmjs.com/package/@shopify/polaris-tokens/v/2.8.0. That _should_ solve your problem. Please let me know if you are able to successfully upgrade

**Comment by danrosenthal** [comment]
Going to go ahead and close this issue, as I've been able to upgrade `polaris-rails` in a WIP PR.

**Comment by lwise** [comment]
Just checked and was able to successfully upgrade; thanks!
